import './Repos.css'
import Repo from './Repo'

const repos = [  {
    "id": 994071002,
    "node_id": "R_kgDOO0BR2g",
    "name": "akanksh-ch.github.io",
    "full_name": "akanksh-ch/akanksh-ch.github.io",
    "private": false,
    "owner": {
      "login": "akanksh-ch",
      "id": 144524423,
      "node_id": "U_kgDOCJ1Ehw",
      "avatar_url": "https://avatars.githubusercontent.com/u/144524423?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/akanksh-ch",
      "html_url": "https://github.com/akanksh-ch",
      "followers_url": "https://api.github.com/users/akanksh-ch/followers",
      "following_url": "https://api.github.com/users/akanksh-ch/following{/other_user}",
      "gists_url": "https://api.github.com/users/akanksh-ch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/akanksh-ch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/akanksh-ch/subscriptions",
      "organizations_url": "https://api.github.com/users/akanksh-ch/orgs",
      "repos_url": "https://api.github.com/users/akanksh-ch/repos",
      "events_url": "https://api.github.com/users/akanksh-ch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/akanksh-ch/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/akanksh-ch/akanksh-ch.github.io",
    "description": "My personal portifolio website",
    "fork": false,
    "url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io",
    "forks_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/forks",
    "keys_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/teams",
    "hooks_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/hooks",
    "issue_events_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/issues/events{/number}",
    "events_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/events",
    "assignees_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/assignees{/user}",
    "branches_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/branches{/branch}",
    "tags_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/tags",
    "blobs_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/languages",
    "stargazers_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/stargazers",
    "contributors_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/contributors",
    "subscribers_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/subscribers",
    "subscription_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/subscription",
    "commits_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/contents/{+path}",
    "compare_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/merges",
    "archive_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/downloads",
    "issues_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/issues{/number}",
    "pulls_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/labels{/name}",
    "releases_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/releases{/id}",
    "deployments_url": "https://api.github.com/repos/akanksh-ch/akanksh-ch.github.io/deployments",
    "created_at": "2025-06-01T06:12:39Z",
    "updated_at": "2025-11-06T16:53:45Z",
    "pushed_at": "2025-11-06T16:53:42Z",
    "git_url": "git://github.com/akanksh-ch/akanksh-ch.github.io.git",
    "ssh_url": "git@github.com:akanksh-ch/akanksh-ch.github.io.git",
    "clone_url": "https://github.com/akanksh-ch/akanksh-ch.github.io.git",
    "svn_url": "https://github.com/akanksh-ch/akanksh-ch.github.io",
    "homepage": "https://akanksh-ch.github.io/",
    "size": 50,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "gpl-3.0",
      "name": "GNU General Public License v3.0",
      "spdx_id": "GPL-3.0",
      "url": "https://api.github.com/licenses/gpl-3.0",
      "node_id": "MDc6TGljZW5zZTk="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
 ]


export default function Repos() {
    return <>
    <ul className='repos'>
        {repos.map(repo => (<li key={repo.id}>
            <Repo json_data={repo} />
        </li>))}
    </ul> 
    </>
}